# Generated by Django 5.1.7 on 2025-04-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_logsheet_on_duty_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='start_date',
            field=models.DateField(default=None),
        ),
    ]
