# Generated by Django 5.1.7 on 2025-03-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_driver_user_type_alter_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
