# Generated by Django 5.1.7 on 2025-04-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_driver_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsheet',
            name='on_duty_start_time',
            field=models.TimeField(null=True),
        ),
    ]
