# Generated by Django 5.1.7 on 2025-04-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_logsheet_on_duty_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='end_coords',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='start_coords',
            field=models.JSONField(null=True),
        ),
    ]
