# Generated by Django 5.1.7 on 2025-03-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_driver_current_cycle_used_driver_driver_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
