# Generated by Django 5.1.7 on 2025-04-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_driver_end_coords_driver_start_coords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='end_coords',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='start_coords',
        ),
    ]
