# Generated by Django 5.1.7 on 2025-03-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_logentry_date_alter_logentry_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
