# Generated by Django 5.1.7 on 2025-03-27 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_logentry_date_alter_logentry_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='lat',
            field=models.FloatField(verbose_name=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='long',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
