# Generated by Django 5.1.7 on 2025-03-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_logentry_lat_alter_logentry_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsheet',
            name='berth',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='logsheet',
            name='driving',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='logsheet',
            name='off_duty',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='logsheet',
            name='on_duty',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='logsheet',
            name='remarks',
            field=models.CharField(default='No Remarks', max_length=10000),
        ),
    ]
