# Generated by Django 5.1.7 on 2025-03-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_logsheet_berth_logsheet_driving_logsheet_off_duty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='date',
        ),
    ]
