# Generated by Django 5.1.7 on 2025-03-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_remove_logentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='point_type',
            field=models.CharField(max_length=50),
        ),
    ]
