# Generated by Django 5.1.7 on 2025-03-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_logentry_point_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='point_type',
        ),
        migrations.AddField(
            model_name='logentry',
            name='activity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
