# Generated by Django 5.1.7 on 2025-04-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_trip_last_refuel_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='last_refuel',
            field=models.DateField(null=True),
        ),
    ]
