# Generated by Django 5.1.7 on 2025-04-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_trip_last_refuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
